confidential-containers/confidential-containers

- governance.md
* Roles defintion
* Steering Committee initial composition
* SC scope and Responsibilities
Fixes #9
Signed-off-by: Samuel Ortiz <samuel.e.ortiz@protonmail.com>
> governance: Initial definition

- .github/ISSUE_TEMPLATE/release-check-list.md
Let's have a release check list template that we can use to track the release steps needed for each new release.
> templates: Add a release check list template

- .github/ISSUE_TEMPLATE/release-check-list.md
Add steps that were added in v0.5.0 (release https://github.com/confidential-containers/community/issues/80#issuecomment-1495661631).
> release-check-list: add AS and KBS steps

- .github/ISSUE_TEMPLATE/release-check-list.md
- Merge steps that can be achieved in a common PR
- Add steps to wait for runtime payload builds
- Add peer pods steps
> release-check-list: Update release checklist

- .github/ISSUE_TEMPLATE/release-check-list.md
- Update the peer pods steps to point to the peer pods specific release docs
- Re-format the checklist to make it easier to read
> Check list updates

- releases/v0.7.0.md
Please suggest any additions
Part of https://github.com/confidential-containers/confidential-containers/issues/111
> releases: add release notes for v0.7.0

- guides/enclave-cc.md
- quickstart.md
Fixes: https://github.com/confidential-containers/enclave-cc/issues/181
- Add the content of deploy KBS cluster and create encrypted image in enclave-cc.md
- Delete verdictd in enclave-cc.md and add cc-kbc and sample-kbc content, and give examples of usage
- Modify the creation of enclave-cc custom resource in quickstart.md
> Update Quickstart for v0.8

- governance.md
> governance: Add my company affiliation

- governance.md
First draft of expansion procedure as discussed last week.
> Add SC expansion protocol

- governance.md
Add Zvonko Kaiser (NVIDIA) to the list of TSC members.
> governance: Update governance.md, add NVIDIA TSC Member

- governance.md
- Add Vincent and Ananya to the list of members.
cc: @vbatts @angarg05
> governance: Add Microsoft TSC members

- .github/workflows/links.yml
Adding a workflow for checking for broken links. I'll fix the existing broken links in a separate PR as some of the fixes are non-trivial and might need discussion.
Fixes #99
> ci: add link checker

- .github/ISSUE_TEMPLATE/release-check-list.md
Fix a few small issues that were noticed during the v0.8.0 process. This checklist is likely to change again for v0.9.0, but we might as well fix it now.
I took out the notes about how you can switch the dependencies to your own branches for testing. I think this is good advice, but not required for doing a release.
Let's wait until we get through everything to merge this.
cc: @portersrc
> Update release checklist issue template

- governance.md
Update membership from Ananya to Dan
Signed-off-by: Ananya Garg <ananyagarg@microsoft.com>
> Update membership from Ananya to Dan

- quickstart.md
Correct the path when deploying KBS.
> quickstart: Correct the path when deploying KBS

- .github/ISSUE_TEMPLATE/release-check-list.md
There are still a number of rough edges here, but this is a big update to the release checklist regarding the upcoming v0.9.0
> update release checklist for v0.9.0

- releases/v0.9.0-alpha0.md
This is an alpha release, so let's be clear about exactly what the limitations are.
> add release notes for v0.9.0-alpha0

- releases/v0.9.0-alpha1.md
A starting point for the release notes. Please lmk if I have left things out.
Part of https://github.com/confidential-containers/confidential-containers/issues/215
> release: add release notes for v0.9.0-alpha1

- releases/v0.9.0.md
I probably forgot a few things so please take a look.
> docs: add release notes for v0.9.0

- ADOPTERS.md
Update ADOPTERS.md：Add NanhuLab to the adopter
> Update ADOPTERS.md：Add NanhuLab to the adopter.

- guides/enclave-cc.md
- trust_model.md
- trust_model_personas.md
With #212 now closed we have a data point that things work fine when the environment is correct. However, we did identify some improvements needed to the docs. Those are added here.
With that, I'm also closing:
Closes: #220 
Closes: #224
Any follow-ups to be had in `Discussions`.
> guides: update enclave-cc notes for SGX hardware mode

- ADOPTERS.md
Adding KubeArmor/5GSEC as adopter.
> adding kubearmor/5gsec as adopter

- ADOPTERS.md
Adding RH to the adopters list
> Adding RH to the adopters list 

- ADOPTERS.md
Add statement agreed by IBM product manager
> doc: Add IBM Z to OSC list

- guides/coco-dev.md
- guides/sev.md
- guides/snp.md
- quickstart.md
Updating the quickstart, SEV, and SNP guides to include instructions on launching CoCo with SEV and SNP memory encryption.
> Update amd docs 

- ADOPTERS.md
Add ByteDance to the list of adopters
> doc: Add ByteDance to the list of adopters

- overview.md
- releases/v0.10.0.md
- releases/v0.11.0.md
- releases/v0.12.0.md
- releases/v0.2.0.md
- releases/v0.3.0.md
- releases/v0.4.0.md
- releases/v0.5.0.md
- releases/v0.6.0.md
- releases/v0.7.0.md
- releases/v0.8.0.md
- releases/v0.9.0-alpha0.md
- releases/v0.9.0-alpha1.md
- releases/v0.9.0.md
We picked up some nice features from Trustee in this release as well as a few other changes.
> release: add release notes for v0.12.0

- .lycheeignore
- ADOPTERS.md
Add Intel to the list of adopters
> doc: Add Intel to the list of adopters

- ADOPTERS.md
ADOPTERS.md : add Switchboard to Service Providers
> ADOPTERS.md : add Switchboard to Service Providers

- releases/v0.13.0.md
Lots of nice updates in this release. Let me know if I missed anything.
> release: release notes for v0.13.0

- releases/v0.15.0.md
Please let me know if there is anything I missed.
Also, did I get the right MSRV?
> release: add release notes for v0.15.0
