MAINTAINERS
This will be updated when we merge our governance PR.
Signed-off-by: Tobin Feldman-Fitzthum <tobin@ibm.com>
=> Add community maintainers

MAINTAINERS
CNCF requires a MAINTAINERS file that matches our steering committee.
Signed-off-by: Dan Middleton <dan.middleton@intel.com>
=> Reconcile steering committee list with MAINTAINERS

.github/ISSUE_TEMPLATE/release-check-list.md
It seems that we have to have a table with some basic information otherwise GitHub won't be able to display the template information to the users.
=> templates: Ensure the release-check-list template is displayed

trust_model.md, trust_model_personas.md
The link to the previous version was broken. Replacing with the latest version v1.3 of the whitepaper.
=> docs: update ccc whitepaper link

CONTRIBUTING.md
The previous link was broken, and the new link is what https://github.com/rust-lang/rustfmt is pointing to.
=> contributing: update Rust style guide

guides/sev.md
Updated the SEV guide with information about the default values of the SEV policy for SEV and SEV-ES as well as the features enabled/disabled.
=> guides/sev: add more details about SEV policy

.github/ISSUE_TEMPLATE/meeting-request.yml
A template to help people request meetings using
the official CoCo Zoom.
Let's try out the fancy new github issue forms.
cc: @fidencio
=> templates: add meeting request issue template

.github/ISSUE_TEMPLATE/release-check-list.md
Contain updates to the Release Checklist as needed to adapt the process for 0.7.0:
* With the merge of image-rs, ocicrypt-rs and attestation-agent into a single guest-components repository, the steps 1,2,3,9,10 and 13 are not necessary anymore. See https://github.com/confidential-containers/confidential-containers/issues/111#issuecomment-1635170840
=> Updates to Release Checklist after 0.7.0

governance.md
The previous link would open an empty document.  Instead of doing that, let's point to the TSC meeting agenda document, so users searching for it can have an easier time finding it from the project's GitHub page.
Fixes: #148
=> governance: Point to an existing TSC meeting agenda document

governance.md
Recognizing Fabiano's (@fidencio) and Mikko's (@mythi) leadership in the community Intel is updating our representation on the Steering Committee. 
Fabiano will replace me now with the intent that Mikko take the next rotation to represent Intel.
_(I will continue my presence in CoCo submitting low quality PRs.. just not on the SC. 😄 )_
=> Update intel rep to steering committee

guides/sev.md
Docker in Ubuntu [has also moved](https://docs.docker.com/compose/install/linux/) to a plugin-based system and, most importantly, has dropped the dash in `docker compose`.
=> docs: correct `docker compose` usage and installation instructions for Debian

CONTRIBUTING.md
A few weeks ago we discussed updating our contributor guide. I took a look at the document and ended up making fairly widespread changes.
I removed all the bits that apply to Kata but not to confidential containers. I also removed some things, like GitHub setup, that aren't unique to our project (although I left a link to some instructions).
I changed the tone of the guide to hopefully be more welcoming.
Please leave any feedback you have.
=> docs: overhaul contributing guide

demos/ssh-demo/k8s-cc-ssh.yaml
This is needed in order to ensure the nydus-snapshotter will behave properly when it's set in the runtime handler.
=> demos: Add io.containerd.cri.runtime-handler to the ssh demo

quickstart.md
This PR updates the docker compose command to avoid failures while running `docker-compose` which is not a valid command.
=> quickstart: Update docker compose command

.github/ISSUE_TEMPLATE/release-check-list.md
On last release I created a document on CoCo's operator explaining how the bundle can be updated to the Operator Hub. Updated this release check-list to link to that document.
=> release-check-list: add pointer to operatorhub doc

governance.md
Adding @ryansavino as the second representative for AMD.
=> Updating AMD Representation

governance.md
As I consider the merge to main really close to be finished at this point, and the most important things to come, at least for Intel, are related to ITA support on Trustee and, of course, Confidential Containers incubation, I'd like to nominate Mikko Ylinen to take my seat during this time.
I do believe that Peter Zhu and Mikko Ylinen are the key pieces to be representing Intel as part of the short-term future. :-)
Meanwhile, I'll still be around and contributing, but from the back seat, allowing Mikko and Peter to focus on the current goals.
With that said, please, join me to welcome Mikko to the Confidential Containers SC!
=> governance: Update Intel's representation

guides/ibm-se.md, quickstart.md
This PR migrates the documentation for IBM Secure Execution from the [operator](https://github.com/confidential-containers/operator/blob/main/docs/how-to/INSTALL-CC-WITH-IBM-SE.md) to the confidential-containers repo. It will be referred by the QuickStart in #236.
Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>
CC: @magowan
=> docs: Add guide for IBM Secure Execution

quickstart.md
fix #196
label should be node.kubernetes.io/worker
searched all `kubernetes.io/worker` in the org https://github.com/search?q=org%3Aconfidential-containers+kubernetes.io%2Fworker&type=code
all are using `node.kubernetes.io/worker`
=> Doc update: correct worker node label

releases/v0.10.0.md
Currently pending until peer pods release status clarifies ([step 3](https://github.com/confidential-containers/confidential-containers/issues/242)) and operator release is actually cut ([step 6](https://github.com/confidential-containers/confidential-containers/issues/242))
=> Release: v0.10.0 release notes

governance.md
And tweak the wording to refer to GitHub teams.
This will need to be approved by a lot of people. 
@confidential-containers/tsc
=> Update governance to allow removing inactive maintainers

README.md
The old links are redirects to the new ones. The new ones are used by OpenSSF in their project related emails.
=> README: update OpenSSF Best Practices Badge URLs

guides/ephemeral_storage.md
The link checker flagged these links. We don't really use these guides as documentation anymore. The website is preferred. Since we don't have a corresponding page on the website (and secure storage support is in flux), let's just delete these links rather than removing the entire file.
This should unblock #318 and #317
=> guides: remove link to CCv0 pages
